# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: blockchain_region_param_v1.proto, region.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


class RegionSpreading(betterproto.Enum):
    SF_INVALID = 0
    SF7 = 1
    SF8 = 2
    SF9 = 3
    SF10 = 4
    SF11 = 5
    SF12 = 6


class Region(betterproto.Enum):
    US915 = 0
    EU868 = 1
    EU433 = 2
    CN470 = 3
    CN779 = 4
    AU915 = 5
    AS923_1 = 6
    KR920 = 7
    IN865 = 8
    AS923_2 = 9
    AS923_3 = 10
    AS923_4 = 11
    AS923_1B = 12
    CD900_1A = 13
    RU864 = 14
    EU868_A = 15
    EU868_B = 16
    EU868_C = 17
    EU868_D = 18
    EU868_E = 19
    EU868_F = 20
    AU915_SB1 = 21
    AU915_SB2 = 22
    AS923_1A = 23
    AS923_1C = 24
    AS923_1D = 25
    AS923_1E = 26
    AS923_1F = 27
    UNKNOWN = 99


@dataclass(eq=False, repr=False)
class BlockchainRegionParamsV1(betterproto.Message):
    region_params: List["BlockchainRegionParamV1"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class TaggedSpreading(betterproto.Message):
    region_spreading: "RegionSpreading" = betterproto.enum_field(1)
    max_packet_size: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class BlockchainRegionSpreadingV1(betterproto.Message):
    tagged_spreading: List["TaggedSpreading"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class BlockchainRegionParamV1(betterproto.Message):
    channel_frequency: int = betterproto.uint64_field(1)
    """in hertz"""

    bandwidth: int = betterproto.uint32_field(2)
    """in hertz"""

    max_eirp: int = betterproto.uint32_field(3)
    """in dBi x 10"""

    spreading: "BlockchainRegionSpreadingV1" = betterproto.message_field(4)
    """list of atoms"""
