services:
  chirpstack-hpr-v2:
    image: ccall48/chirpstack-hpr-v2:latest
    container_name: chirpstack-hpr-v2
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ${HELIUM_KEYPAIR_PATH}:/app/delegate_key.bin:ro
    environment:
      # Helium (Required)
      - HELIUM_CONFIG_HOST=${HELIUM_CONFIG_HOST}
      - HELIUM_KEYPAIR_BIN=${HELIUM_KEYPAIR_BIN}
      - HELIUM_NET_ID=${HELIUM_NET_ID}
      - HELIUM_OUI=${HELIUM_OUI}
      - HELIUM_MAX_COPIES=${HELIUM_MAX_COPIES}
      - ROUTE_ID=${ROUTE_ID}
      # ChirpStack (Required)
      - CHIRPSTACK_SERVER=${CHIRPSTACK_SERVER}
      - CHIRPSTACK_APIKEY=${CHIRPSTACK_APIKEY}
      - REDIS_HOST=${REDIS_HOST}
    command: sh -c 'cd /app && python app.py'

  redis-hpr-v2:
    image: redis:8-alpine
    container_name: redis-hpr-v2
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - ./data:/data

networks:
  default:
    name: core-infra
    external: true
