# .gitea/workflows/build.yaml
name: Build and push image

on:
  push:
    branches:
        - master

jobs:
  deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /app
    steps:
      - name: Set git remote if not already set
        run: git remote -v | grep -w gitea || git remote add gitea "./gitea/git/repositories/${GITHUB_REPOSITORY,,}.git"

      - name: Checkout repo
        run: git pull gitea master

      - name: Deploy
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t ccall48/chirpstack-hpr-v2:latest .
          docker push ccall48/chirpstack-hpr-v2

# .gitea/workflows/build.yaml
# name: Gitea Actions Chirpstack-hpr-v2
# 
# run-name: ${{ github.actor }} is running Gitea Actions 🚀
# 
# on:
#   push:
#     branches:
#       - main
#       - 'releases/**'
# 
# 
# name: Build Contaner Image
# on:
# 
#   # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
#   release:
#     types: [ published ]
# 
#   # publish on pushes to the main branch (image tagged as "latest")
#   push:
#     branches:
#       - master
# 
# jobs:
#   docker_publish:
#     runs-on: "ubuntu-20.04"
# 
#     steps:
#       - uses: actions/checkout@v4
#
#       password: ${{ secrets.DOCKER_PASSWORD }}
# 
#       ## https://github.com/marketplace/actions/push-to-ghcr
#       #- name: Build and publish a Docker image for ${{ github.repository }}
#       #  uses: macbre/push-to-ghcr@master
#       #  with:
#       #    image_name: ${{ github.repository }}  # it will be lowercased internally
#       #    github_token: ${{ secrets.GH_TOKEN }}