name: ci

on:
  push:
    branches:
        - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ccall48/chirpstack-hpr-v2:latest
            ccall48/chirpstack-hpr-v2:${{ gitea.sha  }}
